spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog-main.xml

#https://github.com/Lincoln13/spring-security-jdbc/tree/main/src/main/java/com/example/authdb/service